### ISSUE TITLE
error after upgrading to 0.6.9

### ISSUE THREAD

**Issue by shelper** [python-mode/python-mode#130]
after upgrade to 0.6.9
when i start my gvim , it gives the following error msg. 
thanks!

```
Error detected while processing ...\python-mode\plugin\pymode.vim:
line  118: 
Traceback (most recent call last):
File "<string>", line 1, in <module>
ImportError: cannot import name check_file
```
